#
# Makefile for ROSY drivers
#

obj-$(CONFIG_FINGERPRINT_ROSY)	+= fingerprint/
obj-$(CONFIG_TOUCHSCREEN_ROSY)	+= touchscreen/
obj-$(CONFIG_LED_ROSY)		+= led/
obj-$(CONFIG_SOC_ROSY)		+= soc/
obj-$(CONFIG_POWER_ROSY)	+= power/
obj-$(CONFIG_REGULATOR_ROSY)	+= regulator/
obj-$(CONFIG_SOUND_ROSY)	+= sound/
