obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_ic_table.o
obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_test.o
obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_test_detail_threshold.o
obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_test_global.o
obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_test_ini.o
obj-$(CONFIG_FT8006M_ROSY)	+= focaltech_test_main.o
